version: "3"
services:

  postgres:
    image: postgres:12.1-alpine
    container_name: mypostgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wasmdb
      LANG: ru_RU.UTF-8
      LANGUAGE: ru_RU.UTF-8
      LC_ALL: ru_RU.UTF-8
      POSTGRES_INITDB_ARGS: '-E UTF-8'
  
  consul:
    image: consul
    container_name: dev-consul
    restart: on-failure
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_AGENT_MODE: 'server'
      CONSUL_ENABLE_UI: 'true'
      CONSUL_BOOTSTRAP_EXPECT: 1
      CONSUL_CLIENT_LAN_ADDRESS: 0.0.0.0
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    entrypoint: redis-server --appendonly yes --requirepass redispass123
    restart: on-failure

  consul-loader:
    depends_on:
      - "consul"
    container_name: consul-loader
    image: consul-loader
    entrypoint: dotnet app/BlazorWasmApp.ConsulLoader.dll dev
    restart: "no"

volumes:
  postgres-volume:
    external: true
  redis-volume:
    external: true