version: "3"
services:

  consul:
    image: consul
    container_name: dev-consul
    restart: on-failure
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_AGENT_MODE: 'server'
      CONSUL_ENABLE_UI: 'true'
      CONSUL_BOOTSTRAP_EXPECT: 1
      CONSUL_CLIENT_LAN_ADDRESS: 0.0.0.0
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    entrypoint: redis-server --appendonly yes
    restart: on-failure

volumes:
  postgres-volume:
    external: true
  redis-volume:
    external: true